name: saltstack-dovecot-formula
source: https://github.com/bechtoldt/saltstack-dovecot-formula
summary: SaltStack Formula to set up and configure Dovecot, an IMAP and POP3 email server
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
